nodeLinker: node-modules

# Allow only packages older than 14 days (in minutes). Schema declares that "14d" can be entered, but that doesn't have any effect.
npmMinimalAgeGate: 20160

npmPreapprovedPackages:
  - "@evolu/*"
  - "kysely@0.28.15" # kysely@0.28.15 bugfix needed in Evolu. The exception can be deleted after 2026-04-15

packageExtensions:
  "@trezor/device-authenticity@*":
    dependencies:
      tslib: "^2.6.2"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
