services:
    db:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_GATE_USER}
            POSTGRES_PASSWORD: ${POSTGRES_GATE_PASSWORD}
            PGDATA: /data/postgres
            POSTGRES_DB: ${POSTGRES_GATE_DB}
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -d postgres']
            interval: 30s
            timeout: 10s
            retries: 5

    prometheus:
        image: prom/prometheus
        network_mode: host
        configs:
            - source: prometheus_config
              target: /etc/prometheus/prometheus.yml

configs:
    prometheus_config:
        content: |
            global:
                scrape_interval: 30s

            scrape_configs:
                - job_name: trezor-suite-sync-metrics
                  static_configs:
                      - targets:
                            - localhost:4003
