import { type Result, type Sqlite, type SqliteError, String, brand, ok, sql } from '@evolu/common';

/**
 * Session is generated by client, only used to pair requests.
 */
export const SessionId = brand('SessionId', String);
export type SessionId = typeof SessionId.Type;

/**
 * Random string, that is generated and provided by server.
 * It is used for Authenticity Proof, to validate that Device
 * is genuine and has the valid secure element key.
 *
 * Todo: Add validation, probably pattern: '^[a-fA-F0-9]{32}$',
 */
export const Challenge = brand('Challenge', String);
export type Challenge = typeof Challenge.Type;

export type ChallengeStorage = {
    validateAndConsumeChallenge: (
        sessionId: SessionId,
        challenge: Challenge,
    ) => Result<boolean, SqliteError>;
    storeChallenge: (
        sessionId: SessionId,
        challenge: Challenge,
        expiresInSeconds?: number,
    ) => Result<void, SqliteError>;
    cleanupExpiredChallenges: () => Result<void, SqliteError>;
};

const CHALLENGES_TABLE_NAME = 'challenges';
const DEFAULT_EXPIRATION_SECONDS = 30;

const createChallengesTableQuery = sql`
    create table if not exists ${sql.identifier(CHALLENGES_TABLE_NAME)} (
        sessionId text primary key,
        challenge text not null,
        createdAt integer not null
    ) strict;
`;

export type ChallengeStorageDependencies = {
    sqlite: Sqlite;
    createTime?: () => number;
};

// Todo: split to functions, similar to LimitStorage

export const createChallengeStorage = ({
    sqlite,
    createTime = () => Date.now(),
}: ChallengeStorageDependencies): Result<ChallengeStorage, SqliteError> => {
    const createTableResult = sqlite.exec(createChallengesTableQuery);

    if (!createTableResult.ok) {
        return createTableResult;
    }

    const deleteChallenge = (sessionId: SessionId): Result<void, SqliteError> => {
        const deleteResult = sqlite.exec(sql`
            DELETE FROM ${sql.identifier(CHALLENGES_TABLE_NAME)} 
            WHERE sessionId = ${sessionId}
        `);

        return deleteResult.ok ? ok(undefined) : deleteResult;
    };

    return ok({
        storeChallenge: (
            sessionId: SessionId,
            challenge: Challenge,
            expiresInSeconds: number = DEFAULT_EXPIRATION_SECONDS,
        ): Result<void, SqliteError> => {
            const now = createTime();

            const result = sqlite.exec(sql`
                INSERT OR REPLACE INTO ${sql.identifier(CHALLENGES_TABLE_NAME)} (sessionId, challenge, createdAt)
                VALUES (${sessionId}, ${challenge}, ${now})
            `);

            return result.ok ? ok(undefined) : result;
        },

        validateAndConsumeChallenge: (
            sessionId: SessionId,
            challenge: Challenge,
        ): Result<boolean, SqliteError> => {
            const now = createTime();
            const expirationThreshold = now - DEFAULT_EXPIRATION_SECONDS * 1000;

            const selectResult = sqlite.exec<{ challenge: string }>(sql`
                SELECT challenge FROM ${sql.identifier(CHALLENGES_TABLE_NAME)} 
                WHERE sessionId = ${sessionId} AND createdAt > ${expirationThreshold}
            `);

            if (!selectResult.ok) {
                return selectResult;
            }

            if (selectResult.value.rows.length === 0) {
                return ok(false);
            }

            const [row] = selectResult.value.rows;

            if (!row || row.challenge !== challenge) {
                return ok(false);
            }

            const deleteResult = deleteChallenge(sessionId);

            if (!deleteResult.ok) {
                return deleteResult;
            }

            return ok(true);
        },

        cleanupExpiredChallenges: (): Result<void, SqliteError> => {
            const now = createTime();
            const expirationThreshold = now - DEFAULT_EXPIRATION_SECONDS * 1000;

            const result = sqlite.exec(sql`
                DELETE FROM ${sql.identifier(CHALLENGES_TABLE_NAME)} 
                WHERE createdAt <= ${expirationThreshold}
            `);

            return result.ok ? ok(undefined) : result;
        },
    });
};
