import { type Result, String, brand, ok } from '@evolu/common';

import { AppDatabase, AppDatabaseDep } from '../limitStorage/createPostgreSql.js';
import { createChallengesTableIfNotExists } from '../limitStorage/tables.js';
import { DatabaseError, dbQuery } from '../utils/dbQuery.js';

/**
 * Session is generated by client, only used to pair requests.
 */
export const SessionId = brand('SessionId', String);
export type SessionId = typeof SessionId.Type;

/**
 * Random string, that is generated and provided by server.
 * It is used for Authenticity Proof, to validate that Device
 * is genuine and has the valid secure element key.
 *
 * Todo: Add validation, probably pattern: '^[a-fA-F0-9]{32}$',
 */
export const Challenge = brand('Challenge', String);
export type Challenge = typeof Challenge.Type;

export type ChallengeStorage = {
    validateAndConsumeChallenge: (
        sessionId: SessionId,
        challenge: Challenge,
    ) => Promise<Result<boolean, DatabaseError>>;
    storeChallenge: (
        sessionId: SessionId,
        challenge: Challenge,
        expiresInSeconds?: number,
    ) => Promise<Result<void, DatabaseError>>;
    cleanupExpiredChallenges: () => Promise<Result<void, DatabaseError>>;
    ensureTables: () => Promise<Result<void, DatabaseError>>;
};

const CHALLENGES_TABLE_NAME = 'challenges';
const DEFAULT_EXPIRATION_SECONDS = 30;

export type ChallengeStorageDeps = AppDatabaseDep & {
    createTime: () => number;
};

export type ChallengeStorageDep = { challengeStorage: ChallengeStorage };

// Todo: AI
// Todo: split to functions, similar to LimitStorage

const deleteChallenge = async ({
    db,
    sessionId,
}: {
    db: AppDatabase;
    sessionId: SessionId;
}): Promise<Result<void, DatabaseError>> => {
    const deleteResult = await dbQuery(() =>
        db.deleteFrom('challenges').where('sessionId', '=', sessionId).execute(),
    );

    return deleteResult.ok ? ok(undefined) : deleteResult;
};

export const createChallengeStorage = (deps: ChallengeStorageDeps): ChallengeStorage => ({
    ensureTables: async () => await createChallengesTableIfNotExists(deps.db),
    storeChallenge: async (
        sessionId: SessionId,
        challenge: Challenge,
        expiresInSeconds: number = DEFAULT_EXPIRATION_SECONDS,
    ): Promise<Result<void, DatabaseError>> => {
        const now = deps.createTime();

        // TODO fix CONSTRAINT err
        const result = await dbQuery(() =>
            deps.db
                .insertInto('challenges')
                .values({
                    sessionId,
                    challenge,
                    createdAt: now,
                })
                .onConflict(oc =>
                    oc.column('sessionId').doUpdateSet({
                        challenge,
                        createdAt: now,
                    }),
                )
                .execute(),
        );

        return result.ok ? ok(undefined) : result;
    },

    validateAndConsumeChallenge: async (
        sessionId: SessionId,
        challenge: Challenge,
    ): Promise<Result<boolean, DatabaseError>> => {
        const now = deps.createTime();
        const expirationThreshold = now - DEFAULT_EXPIRATION_SECONDS * 1000;

        const selectResult = await dbQuery(() =>
            deps.db
                .selectFrom(CHALLENGES_TABLE_NAME)
                .where('sessionId', '=', sessionId)
                .where('createdAt', '>', expirationThreshold)
                .select(['challenge'])
                .execute(),
        );

        if (!selectResult.ok) {
            return selectResult;
        }

        if (selectResult.value.length === 0) {
            return ok(false);
        }

        const [row] = selectResult.value;

        if (!row || row.challenge !== challenge) {
            return ok(false);
        }

        const deleteResult = await deleteChallenge({ db: deps.db, sessionId });

        if (!deleteResult.ok) {
            return deleteResult;
        }

        return ok(true);
    },

    cleanupExpiredChallenges: async (): Promise<Result<void, DatabaseError>> => {
        const now = deps.createTime();
        const expirationThreshold = now - DEFAULT_EXPIRATION_SECONDS * 1000;

        const result = await dbQuery(() =>
            deps.db
                .deleteFrom(CHALLENGES_TABLE_NAME)
                .where('createdAt', '<=', expirationThreshold)
                .execute(),
        );

        return result.ok ? ok(undefined) : result;
    },
});
