import { String, brand } from '@evolu/common';

import { AppDatabaseDep } from '../posgres/createPostgreSql.js';
import {
    CleanupExpiredChallengesDep,
    createCleanupExpiredChallenges,
} from './methods/createCleanupExpiredChallenges.js';
import { createDeleteChallenge } from './methods/createDeleteChallenge.js';
import { StoreChallengeDep, createStoreChallenge } from './methods/createStoreChallenge.js';
import {
    ValidateAndConsumeChallengeDep,
    createValidateAndConsumeChallenge,
} from './methods/createValidateAndConsumeChallenge.js';

/**
 * Session is generated by client, only used to pair requests.
 */
export const SessionId = brand('SessionId', String);
export type SessionId = typeof SessionId.Type;

/**
 * Random string, that is generated and provided by server.
 * It is used for Authenticity Proof, to validate that Device
 * is genuine and has the valid secure element key.
 *
 * Todo: Add validation, probably pattern: '^[a-fA-F0-9]{32}$',
 */
export const Challenge = brand('Challenge', String);
export type Challenge = typeof Challenge.Type;

type CreateChallengeStorageDeps = AppDatabaseDep & {
    createTime: () => number;
};

export type CreateChallengeStorage = StoreChallengeDep &
    ValidateAndConsumeChallengeDep &
    CleanupExpiredChallengesDep;

export type ChallengeStorageDep = { challengeStorage: CreateChallengeStorage };

export const createChallengeStorage = (
    deps: CreateChallengeStorageDeps,
): CreateChallengeStorage => {
    const deleteChallenge = createDeleteChallenge({ db: deps.db });
    const storeChallenge = createStoreChallenge({ db: deps.db, createTime: deps.createTime });
    const validateAndConsumeChallenge = createValidateAndConsumeChallenge({
        db: deps.db,
        createTime: deps.createTime,
        deleteChallenge,
    });
    const cleanupExpiredChallenges = createCleanupExpiredChallenges({
        db: deps.db,
        createTime: deps.createTime,
    });

    return {
        storeChallenge,
        validateAndConsumeChallenge,
        cleanupExpiredChallenges,
    };
};
