import { String, type TypeError, brand, err, ok, utf8ToBytes } from '@evolu/common';

import { AppDatabaseDep } from '../postgres/createPostgreSql.js';
import {
    CleanupExpiredChallengesDep,
    createCleanupExpiredChallenges,
} from './methods/createCleanupExpiredChallenges.js';
import { createDeleteChallenge } from './methods/createDeleteChallenge.js';
import { StoreChallengeDep, createStoreChallenge } from './methods/createStoreChallenge.js';
import {
    ValidateAndConsumeChallengeDep,
    createValidateAndConsumeChallenge,
} from './methods/createValidateAndConsumeChallenge.js';

export interface SessionIdError extends TypeError<'SessionId'> {
    readonly value: string;
}

/**
 * Session is generated by client, only used to pair requests.
 */
export const SessionId = brand(
    'SessionId',
    String,
    value => {
        const len = utf8ToBytes(value).length;

        return len <= 256 ? ok() : err<SessionIdError>({ type: 'SessionId', value });
    },
    () => 'SessionId must be at most 256 bytes long.',
);
export type SessionId = typeof SessionId.Output;

/**
 * Random string, that is generated and provided by server.
 * It is used for Authenticity Proof, to validate that Device
 * is genuine and has the valid secure element key.
 *
 * Todo: Add validation, probably pattern: '^[a-fA-F0-9]{32}$',
 */
export const Challenge = brand('Challenge', String);
export type Challenge = typeof Challenge.Output;

type CreateChallengeStorageDeps = AppDatabaseDep & {
    createTime: () => number;
};

export type CreateChallengeStorage = StoreChallengeDep &
    ValidateAndConsumeChallengeDep &
    CleanupExpiredChallengesDep;

export type ChallengeStorageDep = { challengeStorage: CreateChallengeStorage };

export const createChallengeStorage = (
    deps: CreateChallengeStorageDeps,
): CreateChallengeStorage => {
    const deleteChallenge = createDeleteChallenge({ db: deps.db });
    const storeChallenge = createStoreChallenge({ db: deps.db, createTime: deps.createTime });
    const validateAndConsumeChallenge = createValidateAndConsumeChallenge({
        db: deps.db,
        createTime: deps.createTime,
        deleteChallenge,
    });
    const cleanupExpiredChallenges = createCleanupExpiredChallenges({
        db: deps.db,
        createTime: deps.createTime,
    });

    return {
        storeChallenge,
        validateAndConsumeChallenge,
        cleanupExpiredChallenges,
    };
};
