name: "[Build/Deploy] suite-sync to production server"

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  packages: write
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-suite-sync-image:
    uses: ./.github/workflows/build-and-push-image.yml
    with:
      image_name: suite-sync-prod
      environment: 'prod'
      push: true
      build-args: |
        BUILDKIT_INLINE_CACHE=1

  update-deployment-manifests:
    name: deployment-manifests-backend
    runs-on: ubuntu-latest
    needs:
      - build-suite-sync-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Update to current prod images
        uses: mikefarah/yq@v4.52.4
        with:
          cmd: |
            yq -i '
               (.images[] | select(.name == "538326561891.dkr.ecr.eu-central-1.amazonaws.com/suite-sync").newName) = "${{ needs.build-suite-sync-image.outputs.image_registry }}/suite-sync-prod" |
               (.images[] | select(.name == "538326561891.dkr.ecr.eu-central-1.amazonaws.com/suite-sync").newTag)  = "${{ github.ref_name }}"
            ' .k8s/production/kustomization.yaml

      - name: Generate GitHub App token
        id: trezor-bot-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.TREZOR_BOT_APP_ID }}
          private-key: ${{ secrets.TREZOR_BOT_PRIVATE_KEY }}

      - name: Create Pull Request with updated images
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.trezor-bot-token.outputs.token }}
          commit-message: "[Deployment production] update to current production image tag"
          committer: ${{ steps.trezor-bot-token.outputs.app-slug }}[bot] <208941332+${{ steps.trezor-bot-token.outputs.app-slug }}[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: deploy/${{github.ref_name}}
          base: gitops/prod
          delete-branch: true
          title: "[Deployment production] update current production image tag"
          assignees: ${{ github.actor }}
          draft: false
          labels: |
            ready-to-merge
            deployment
            automated
