name: "[CI] Test"

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-unit:
    runs-on: ubuntu-latest
    if: github.repository == 'trezor/trezor-evolu-relay'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - run: yarn install --immutable
      - run: yarn test

  type-check:
    name: Type Checking
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=6144
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Type Check
        run: |
          yarn install --immutable
          yarn type-check

  lint:
    name: Linting and formatting
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=6144
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Format
        run: |
          yarn install --immutable
          yarn format:check
